
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: todoapp_development
  username: ENV['USERNAME']
  password: ENV['PASSWORD']

test:
  <<: *default
  database: todoapp_test

production:
  <<: *default
  database: todoapp_production
  username: todoapp
  password: <%= ENV['TODOAPP_DATABASE_PASSWORD'] %>
